### ISSUE TITLE
Doesn't work on Tanks & Temples dataset.

### ISSUE THREAD

**Issue by JunsukLee** [FangjinhuaWang/PatchmatchNet#54] opened 2021-11-04 07:03 UTC
Thanks for distributing a good project.
I am impressed with your paper.
The DTU dataset works fine.
However, the following problems occur in the Temple & Tank dataset.
I don't know what the cause is.
Could you help?

RuntimeError: The size of tensor a (208) must match the size of tensor b (207) at non-singleton dimension 2

**Comment by FangjinhuaWang** [comment] 2021-11-04 16:27
Hi,

Thanks for pointing this out. The current function that reads in the images keeps the original ratio during scaling, which cannot make sure that the height and width can be divided by 32. For example, the original image size is 1920x1080, the given size is 1920x1056, the function will output a image with a size 1920x1080. This also causes other problems since the intrinsics are scaled with the given image dimension (e.g. 1920x1056). This is already fixed now. @anmatako

**Comment by anmatako** [comment] 2021-11-04 18:06
@FangjinhuaWang does the size need to be divisible by 32 or 8? I see 3 consecutive divisions by 2 so I'm not sure where the requirement for divisible by 32 is coming from; maybe I'm missing something in the implementation.

**Comment by FangjinhuaWang** [comment] 2021-11-05 06:21
@anmatako You are correct. Divisible by 8 is enough.

**Closed** 2021-11-13 07:15 UTC

**Comment by taohu1994** [comment] 2022-08-20 17:25
Hi, the tankandtemples dataset that your provide doesn't work. The problem is because of the "cams" folder. It name should be "cams", while in the provided tandandtemples dataset, it is "cams_1".

**Comment by FangjinhuaWang** [comment] 2022-08-21 20:24
Hi,

The original dataset is named as "cams_1". You can change the script to match the name.
